# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: wur
  theme_night: wur
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Wageningen University & Research, Biometris'
    description: ''
    twitter: mverouden
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    # Show a language chooser (if you have translated your site content)?
    show_translations: false
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© 2018-{year} Maikel P.H. Verouden. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Mon, Jan 2, 2006'
  time_format: '15:05' # '3:04 PM'
  address_format: nl # en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - python
      - latex
      - bash
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/mverouden/blogdown-academic'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 17

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true # Academicons icon pack https://jpswalsh.github.io/academicons/

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
